# Generated by Django 4.2 on 2025-06-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('Authentication Server', 'Authentication Server'), ('Resource Server', 'Resource Server')], default='user', max_length=30),
        ),
    ]
